name: Update YouTube Stats

on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC
  workflow_dispatch:      # Allows manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run updater script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python main.py

      - name: Run video tracker script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_VIDEO_DB_ID: ${{ secrets.NOTION_VIDEO_DB_ID }}
        run: python video_tracker.py

      - name: Run video importer
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_VIDEO_DB_ID: ${{ secrets.NOTION_VIDEO_DB_ID }}
        run: python video_importer.py


      - name: Commit updated data.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add public/data.json
          git commit -m "Update data.json" || echo "No changes to commit"
          git push
